name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    name: Backend (Node)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test --silent

  frontend:
    name: Frontend (Expo RN - typecheck)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json
      - run: npm ci
      # Run TypeScript typecheck only; Jest for RN often needs native mocks in CI
      - run: npx tsc --noEmit

  ai_service:
    name: AI Service (Python)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ai-service
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt
      - run: python - <<'PY'
import importlib
import sys
mods = ['fastapi','uvicorn','pydantic','numpy','sklearn']
for m in mods:
    importlib.import_module(m)
print('ok')
PY


